## node configurations template
node:
  mode: "miners"
  ## the profile of node: devnet/testnet/mainnet
  profile: "testnet"
  # default chain url for miner, can be overwritten in miners[] as below
  chainWsUrl: "ws://127.0.0.1:9944/"
  # default backup chain urls for miner, can be overwritten in miners[] as below
  backupChainWsUrls: ["wss://testnet-rpc0.cess.cloud/ws/", "wss://testnet-rpc1.cess.cloud/ws/", "wss://testnet-rpc2.cess.cloud/ws/", "wss://testnet-rpc3.cess.cloud/ws/"]

## chain configurations
## set option: '--skip-chain' or '-s' to skip installing chain (mineradm install --skip-chain)
## if set option: --skip-chain, please set official chain in miner[].chainWsUrl or others chain you know
chain:
  ## the name of chain node
  name: "cess"
  ## the port of chain node
  port: 30336
  ## listen rpc service at port 9944
  rpcPort: 9944

## miners configurations  (multi miners mode)
miners:
  - name: "miner1"
    # P2P communication port, each port must be different
    port: 15001
    # Maximum space used, the unit is GiB
    UseSpace: 1000
    # Number of cpu's used, 0 means use all
    UseCpu: 2
    # earnings account
    earningsAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account,
    # otherwise the staking will be paid by the earningsAcc.
    stakingAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Signature account mnemonic
    # each miner's mnemonic should be different
    mnemonic: "aaaaa bbbbb ccccc ddddd eeeee fffff ggggg hhhhh iiiii jjjjj kkkkk lllll"
    # miner work at this path
    diskPath: "/mnt/cess_storage1"
    # The rpc endpoint of the chain
    # `official chain: wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud/ws/ wss://testnet-rpc2.cess.cloud/ws/` wss://testnet-rpc3.cess.cloud/ws/`
    chainWsUrl: "ws://127.0.0.1:9944/"
    backupChainWsUrls: []
    # Priority tee list address
    # Bootstrap Nodes
    Boot: "_dnsaddr.boot-bucket-testnet.cess.cloud"

  - name: "miner2"
    # P2P communication port, each port must be different
    port: 15002
    # Maximum space used, the unit is GiB
    UseSpace: 1000
    # Number of cpu's used
    UseCpu: 2
    # earnings account
    earningsAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account,
    # otherwise the staking will be paid by the earningsAcc.
    stakingAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Signature account mnemonic
    # each miner's mnemonic should be different
    mnemonic: "lllll kkkkk jjjjj iiiii hhhhh ggggg fffff eeeee ddddd ccccc bbbbb aaaaa"
    # miner work at this path
    diskPath: "/mnt/cess_storage2"
    # The rpc endpoint of the chain
    # `official chain: wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud/ws/ wss://testnet-rpc2.cess.cloud/ws/` wss://testnet-rpc3.cess.cloud/ws/`
    chainWsUrl: "ws://127.0.0.1:9944/"
    backupChainWsUrls: []
    # Bootstrap Nodes
    Boot: "_dnsaddr.boot-bucket-testnet.cess.cloud"
