## node configurations template
node:
  ## the mode of node: authority/storage/rpcnode/multibucket
  mode: "multibucket"
  ## the profile of node: devnet/testnet/mainnet
  profile: "testnet"
  # default chain/rpcnode url for bucket, this config will be overwritten in buckets[] as below
  chainWsUrl: ""
  # default backup chain/rpcnode urls for bucket, this config will be overwritten in buckets[] as below
  backupChainWsUrls: []

## chain/rpcnode configurations
## set option: '--skip-rpcnode' or '-s' to skip installing rpcnode
## if set option: --skip-rpcnode, please set official rpcnode in bucket[].rpcNodeWsUrl
rpcnode:
  ## the name of chain/rpcnode node
  name: "cess"
  ## the port of chain/rpcnode node
  port: 30336
  ## listen rpc service at port 9944
  rpcPort: 9944

## bucket configurations  (multi storage miner mode)
buckets:
  # P2P communication port
  - name: "bucket_1"
    port: 15001
    # Maximum space used, the unit is GiB
    UseSpace: 1000
    # Number of cpu's used, 0 means use all
    UseCpu: 2
    # earnings account
    earningsAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account,
    # otherwise the staking will be paid by the signature account.
    stakingAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Signature account mnemonic
    # each bucket's mnemonic should be different
    mnemonic: "aaaaa bbbbb ccccc ddddd eeeee fffff ggggg hhhhh iiiii jjjjj kkkkk lllll"
    # a directory mount with filesystem
    diskPath: "/mnt/cess_storage1"
    # The rpc endpoint of the rpcnode
    # `official rpcnode: wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud/ws/ wss://testnet-rpc2.cess.cloud/ws/`
    rpcNodeWsUrl: "ws://127.0.0.1:9944/"
    backupRpcNodeWsUrls: []
    # Priority tee list address
    TeeList:
      - "127.0.0.1:8080"
      - "127.0.0.1:8081"
    # Bootstrap Nodes
    Boot: "_dnsaddr.boot-bucket-testnet.cess.cloud"

  - name: "bucket_2"
    # P2P communication port
    port: 15002
    # Maximum space used, the unit is GiB
    UseSpace: 1000
    # Number of cpu's used
    UseCpu: 2
    # earnings account
    earningsAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Staking account
    # If you fill in the staking account, the staking will be paid by the staking account,
    # otherwise the staking will be paid by the signature account.
    stakingAcc: "cXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # Signature account mnemonic
    # each bucket's mnemonic should be different
    mnemonic: "lllll kkkkk jjjjj iiiii hhhhh ggggg fffff eeeee ddddd ccccc bbbbb aaaaa"
    # a directory mount with filesystem
    diskPath: "/mnt/cess_storage2"
    # The rpc endpoint of the rpcnode
    # `official rpcnode: wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud/ws/ wss://testnet-rpc2.cess.cloud/ws/`
    rpcNodeWsUrl: "ws://127.0.0.1:9944/"
    backupRpcNodeWsUrls: [ ]
    # Priority tee list address
    TeeList:
      - "127.0.0.1:8080"
      - "127.0.0.1:8081"
    # Bootstrap Nodes
    Boot: "_dnsaddr.boot-bucket-testnet.cess.cloud"
